//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPFileType.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPFileType.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebP encoder API version mismatch..
        /// </summary>
        internal static string ApiVersionMismatch {
            get {
                return ResourceManager.GetString("ApiVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total file size must be less than 4GB.
        /// </summary>
        internal static string EncoderFileTooBig {
            get {
                return ResourceManager.GetString("EncoderFileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when encoding the WebP file..
        /// </summary>
        internal static string EncoderGenericError {
            get {
                return ResourceManager.GetString("EncoderGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Quality / Speed.
        /// </summary>
        internal static string EncodingMethod {
            get {
                return ResourceManager.GetString("EncodingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Passes.
        /// </summary>
        internal static string EncodingPasses {
            get {
                return ResourceManager.GetString("EncodingPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size in bytes.
        /// </summary>
        internal static string FileSizeText {
            get {
                return ResourceManager.GetString("FileSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Strength.
        /// </summary>
        internal static string FilterStrengthText {
            get {
                return ResourceManager.GetString("FilterStrengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string FilterTypeSimpleText {
            get {
                return ResourceManager.GetString("FilterTypeSimpleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string FilterTypeStrongText {
            get {
                return ResourceManager.GetString("FilterTypeStrongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Type.
        /// </summary>
        internal static string FilterTypeText {
            get {
                return ResourceManager.GetString("FilterTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient memory to save the image..
        /// </summary>
        internal static string InsufficientMemoryOnSave {
            get {
                return ResourceManager.GetString("InsufficientMemoryOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimensions of a WebP image must be 16383x16383 or less..
        /// </summary>
        internal static string InvalidImageDimensions {
            get {
                return ResourceManager.GetString("InvalidImageDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter..
        /// </summary>
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WebP Image..
        /// </summary>
        internal static string InvalidWebPImage {
            get {
                return ResourceManager.GetString("InvalidWebPImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string QualityText {
            get {
                return ResourceManager.GetString("QualityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpness .
        /// </summary>
        internal static string SharpnessText {
            get {
                return ResourceManager.GetString("SharpnessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string WebPPreset_Text {
            get {
                return ResourceManager.GetString("WebPPreset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string WebPPresetDefault_Text {
            get {
                return ResourceManager.GetString("WebPPresetDefault_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        internal static string WebPPresetDrawing_Text {
            get {
                return ResourceManager.GetString("WebPPresetDrawing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string WebPPresetIcon_Text {
            get {
                return ResourceManager.GetString("WebPPresetIcon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string WebPPresetPhoto_Text {
            get {
                return ResourceManager.GetString("WebPPresetPhoto_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string WebPPresetPicture_Text {
            get {
                return ResourceManager.GetString("WebPPresetPicture_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string WebPPresetText_Text {
            get {
                return ResourceManager.GetString("WebPPresetText_Text", resourceCulture);
            }
        }
    }
}
